spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/your_database
    password: your_password
    username: your_username
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0

wfs-safe-cache:
  bloom-filter:
    max-amount-of-inserted-data: 200
  redis:
    unified-config: false
    database: 1